#ifndef CONST_H
#define CONST_H

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 600
#define CELL_WIDTH 80
#define CELL_HEIGHT 100
#define BOTTOM_BAR_HEIGHT 25
#define SPEED_ACCELERATE 0.2
#define SPEED_MIN 2
#define SPEED_MAX 10
#define NUM_OF_CELL_X SCREEN_WIDTH/CELL_WIDTH
#define NUM_OF_CELL_Y SCREEN_HEIGHT/CELL_HEIGHT

#endif // CONST_H
