#ifndef CONST_H
#define CONST_H

#define SCREEN_WIDTH 400
#define SCREEN_HEIGHT 600
#define CELL_WIDTH 80
#define CELL_HEIGHT 100
#define BOTTOM_BAR_HEIGHT 25
#define SPEED_ACCELERATE 0.0005
#define SPEED_MIN 2
#define SPEED_MAX 10
#define NUM_OF_CELL_X SCREEN_WIDTH/CELL_WIDTH
#define NUM_OF_CELL_Y SCREEN_HEIGHT/CELL_HEIGHT
#define LIVES_MAX 20
#define MAX_NOTE 68
#define MAX_VOICE 3

#endif // CONST_H
